# Generated by Django 3.1.7 on 2021-03-01 22:25

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_packagetype_thumbnail'),
        ('destinations', '0010_auto_20210209_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='picture',
        ),
        migrations.AddField(
            model_name='country',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.FileField(default='', upload_to='images/countries/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='package_type',
            field=models.ManyToManyField(to='packages.PackageType'),
        ),
        migrations.AddField(
            model_name='country',
            name='show_tab_holidays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='show_tab_overview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='show_tab_reason_why',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='show_tab_tour_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='show_tab_what_to_do',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='show_tab_when_to_go',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='name', unique_with=['name']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.FileField(default='', upload_to='images/countries/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
    ]
