# Generated by Django 3.1.7 on 2021-03-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_auto_20210301_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['order'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='destination',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
