# Generated by Django 3.1.7 on 2021-03-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0024_auto_20210302_0405'),
        ('destinations', '0013_auto_20210302_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='interest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='packages.interest'),
        ),
    ]
