# Generated by Django 3.1.7 on 2021-03-04 03:42

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0014_reason_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='weather_content',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='WeatherItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='', max_length=100)),
                ('degrees', models.IntegerField(default=0)),
                ('rain', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destinations.destination')),
            ],
            options={
                'db_table': 'weather_items',
            },
        ),
    ]
