# Generated by Django 3.1.7 on 2021-03-05 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0015_auto_20210304_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='reasons',
        ),
        migrations.AddField(
            model_name='destination',
            name='is_what_to_do',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_why_reason',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reason',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='weatheritems',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='destinations.destination'),
        ),
    ]
