# Generated by Django 3.2.4 on 2021-08-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0019_continentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='quote',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
