# Generated by Django 3.2.4 on 2021-08-26 16:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0020_country_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='quote',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
    ]
