# Generated by Django 3.2.4 on 2021-08-26 20:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0021_alter_country_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='travelfact',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
    ]
