# Generated by Django 3.2.4 on 2021-08-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0022_destination_travelfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqdest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faqdest',
            name='onTravel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faqdest',
            name='postTravel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faqdest',
            name='preTravel',
            field=models.BooleanField(default=False),
        ),
    ]
