# Generated by Django 3.2.4 on 2021-08-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0023_auto_20210826_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereToGo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='', max_length=150)),
                ('image', models.FileField(upload_to='images/where-to-go/')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='where', to='destinations.destination')),
            ],
            options={
                'db_table': 'wheretogo',
            },
        ),
    ]
