# Generated by Django 3.2.4 on 2021-08-27 16:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0026_auto_20210827_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheretogo',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
    ]
