# Generated by Django 3.2.4 on 2021-08-27 17:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0028_alter_wheretogo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwhere',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
