# Generated by Django 3.2.4 on 2021-09-03 20:04

import autoslug.fields
import destinations.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0030_auto_20210827_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwhere',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='null', upload_to=destinations.models.path_and_rename_itemWhere),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wheretogo',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True),
        ),
    ]
