# Generated by Django 3.2.4 on 2021-09-13 09:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0031_auto_20210903_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travelfact',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='null'),
            preserve_default=False,
        ),
    ]
