# Generated by Django 3.2.4 on 2021-09-16 13:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0033_auto_20210913_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travelAdvice',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='null'),
            preserve_default=False,
        ),
    ]
