# Generated by Django 3.2.4 on 2021-09-27 16:26

import destinations.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0035_traveladvice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=destinations.models.path_and_rename_subDestination)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subDestination', to='destinations.destination')),
            ],
            options={
                'db_table': 'subDestination',
            },
        ),
    ]
