# Generated by Django 3.2.4 on 2021-09-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0036_subdestination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubDestination',
        ),
    ]
