# Generated by Django 3.2.4 on 2022-01-27 15:33

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0037_delete_subdestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighLigths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='', max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('image', models.FileField(upload_to='images/highligths/')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='highligths', to='destinations.destination')),
            ],
            options={
                'verbose_name_plural': 'highligths - Items',
                'db_table': 'highligths',
            },
        ),
    ]
