# Generated by Django 3.2.4 on 2022-01-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0038_highligths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highligths',
            options={'verbose_name_plural': 'highligths'},
        ),
    ]
