# Generated by Django 3.2.4 on 2022-03-29 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0040_auto_20220328_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='continentimage',
            name='continent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.continent'),
        ),
    ]
