# Generated by Django 3.2.4 on 2022-04-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0041_continentimage_continent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
    ]
