# Generated by Django 3.2.4 on 2022-04-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0041_continentimage_continent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        # migrations.RemoveField(
        #     model_name='country',
        #     name='package_type',
        # ),
        # migrations.RemoveField(
        #     model_name='country',
        #     name='show_tab_holidays',
        # ),
        # migrations.RemoveField(
        #     model_name='country',
        #     name='show_tab_overview',
        # ),
        # migrations.RemoveField(
        #     model_name='country',
        #     name='show_tab_reason_why',
        # ),
        # migrations.RemoveField(
        #     model_name='country',
        #     name='show_tab_tour_in',
        # ),
        # migrations.RemoveField(
        #     model_name='country',
        #     name='show_tab_what_to_do',
        # ),
        # migrations.RemoveField(
        #     model_name='country',
        #     name='show_tab_when_to_go',
        # ),
    ]
