# Generated by Django 3.2.4 on 2022-04-01 16:55

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0041_continentimage_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('quote', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique_with=['name'])),
                ('image', models.FileField(upload_to='images/countries/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Continents',
                'db_table': 'country',
                'ordering': ['order'],
            },
        ),
    ]
