# Generated by Django 3.2.4 on 2022-04-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0042_auto_20220401_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
