# Generated by Django 3.2.4 on 2021-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_auto_20210201_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OptionalRenting',
        ),
    ]
