# Generated by Django 3.2.4 on 2021-07-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_auto_20210715_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryimage',
            options={'ordering': ['order']},
        ),
    ]
