# Generated by Django 3.2.4 on 2021-12-10 20:02

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('job', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('hobbies', tinymce.models.HTMLField(default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='full_name', unique_with=['name'])),
                ('image', models.FileField(null=True, upload_to='images/ourteam/')),
            ],
            options={
                'db_table': 'collaborators',
                'ordering': ['order'],
            },
        ),
    ]
