# Generated by Django 3.2.4 on 2021-12-14 20:42

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('keywords', models.TextField(default='')),
                ('titleSEO', models.TextField(blank=True, default='', max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['title'])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'page',
            },
        ),
    ]
