# Generated by Django 3.1.7 on 2021-03-01 22:13

from django.db import migrations
import imagekit.models.fields
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0022_package_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=packages.models.path_and_rename),
        ),
    ]
