# Generated by Django 3.1.7 on 2021-03-02 04:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_packagetype_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='package-types'),
        ),
    ]
