# Generated by Django 3.1.7 on 2021-03-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0024_auto_20210302_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='atypical',
            field=models.BooleanField(default=False),
        ),
    ]
