# Generated by Django 3.1.7 on 2021-03-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0016_auto_20210305_0441'),
        ('packages', '0026_package_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='destinations.country'),
        ),
    ]
