# Generated by Django 3.2.4 on 2021-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0028_auto_20210525_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
