# Generated by Django 3.2.4 on 2021-09-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0030_auto_20210916_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='package_types',
        ),
    ]
