# Generated by Django 3.2.4 on 2021-09-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0031_remove_interest_package_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/package_type/'),
        ),
    ]
