# Generated by Django 3.2.4 on 2021-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0032_packagetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
