# Generated by Django 3.2.4 on 2021-09-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0034_remove_packagetype_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
