# Generated by Django 3.2.4 on 2021-09-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0035_delete_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='atypical',
            new_name='featured',
        ),
        migrations.RemoveField(
            model_name='package',
            name='show_specialist',
        ),
    ]
