# Generated by Django 3.2.4 on 2022-01-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0037_package_where_to_go'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='activity',
            field=models.IntegerField(choices=[(1, 'Very High'), (2, 'High'), (3, 'Moderate'), (4, 'Low')], default=1),
        ),
    ]
