# Generated by Django 3.2.4 on 2022-03-17 19:15

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0038_alter_package_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='descriptionSEO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='keywordsSEO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='title', unique_with=['title']),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='titleSEO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
