# Generated by Django 3.2.4 on 2022-03-17 19:40

from django.db import migrations
import imagekit.models.fields
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0039_auto_20220317_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=packages.models.path_and_rename_packageType),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=packages.models.path_and_rename_packageType),
        ),
    ]
