# Generated by Django 3.2.4 on 2022-03-29 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0040_auto_20220317_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='country',
        ),
    ]
