# Generated by Django 3.2.4 on 2021-11-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211115_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_type',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogtype'),
        ),
    ]
