# Generated by Django 3.2.4 on 2021-11-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211115_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time_reading',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
