# Generated by Django 3.2.4 on 2021-11-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_time_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
