# Generated by Django 3.2.4 on 2021-11-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_time_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time_reading',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
