# Generated by Django 3.2.4 on 2021-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0005_contactus_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsB2C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('number', models.CharField(default='', max_length=255)),
                ('package', models.CharField(default='', max_length=255)),
                ('message', models.TextField(default='', max_length=999)),
                ('extra_data', models.TextField(default='', max_length=999)),
                ('is_newsletter', models.BooleanField(default=False)),
                ('is_promo', models.BooleanField(default=False)),
                ('url', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_usB2C',
            },
        ),
    ]
