# Generated by Django 3.2.4 on 2022-04-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0006_contactusb2c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='country_residence',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='contactusb2c',
            old_name='number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='contactus',
            name='company',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='typeClient',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactusb2c',
            name='company',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactusb2c',
            name='typeClient',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='specialist',
            name='calendly',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='package',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
